# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: catalogo_development
  pool: 5
  username: postgres
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: catalogo_production
  pool: 5
  username: postgres
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: catalogo_test
  pool: 5
  username: postgres
  password: 123